apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.project.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.application.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name }}
      name: {{ .Values.application.name }}
      namespace: {{ .Values.project.name }}
    spec:
      containers:
        - env:
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.postgresql.database }}
            - name: POSTGRESQL_PASSWORD
              value: {{ .Values.postgresql.password }}
            - name: POSTGRESQL_USER
              value: {{ .Values.postgresql.user }}
          image: registry.redhat.io/rhel8/postgresql-13
          name: {{ .Values.application.name }}
